language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy

before_script:
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.7.2/gnatsd-v0.7.2-linux-amd64.tar.gz -O gnatsd.tar.gz
  - tar -xvf gnatsd.tar.gz
  - ./gnatsd &

install:
  - travis_retry pip install --upgrade .

script: py.test

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - python: pypy
